### ISSUE TITLE
Adding a Release Tag

### ISSUE THREAD

**Issue by ORichterSec** [dj-on-github/hexbinhex#2]
Hello,
I wanted to ask if it is possible for you to add a release tag to this project? Maybe just something simple like "v1.0" or what you prefer (maybe similar another one of your projects like djent https://github.com/dj-on-github/djent/releases/tag/1.0)?
That would give users the possibility to refer to the release instead of a rev-hash, when automatically pulling the code. That would be useful for example for someone when packaging this project for the 'nix' package manager (https://github.com/NixOS/nixpkgs).

**Comment by dj-on-github** [comment]
Yep. I didn't know this code had reached the exhaulted state of being known by package managers. I'll take a day to think about what to tag it with - not because I need to, but I'm on vacation right now and I have priorities.

**Comment by ORichterSec** [comment]
That is nice to hear. I mean it is not a time sensitive matter. So enjoy your vacation!

**Comment by dj-on-github** [comment]
v1.0 tag created associated with a release 1.0.
