### ISSUE TITLE
Error when building target "install": Makefile references source file 'bin2dec.c' which does not exist

### ISSUE THREAD

**Issue by ORichterSec** [dj-on-github/hexbinhex#3]
Hello there,
when i tried to build the target "install" with the 1.0 release i got following error:
`> make: *** No rule to make target 'bin2dec.c', needed by 'bin2dec'.  Stop.`

It comes from that line in the makefile:
https://github.com/dj-on-github/hexbinhex/blob/09e22e6154d29286da11c0de09aa3777993bc73e/Makefile#L26
The problem is that there is no source file named 'bin2dec.c' in the repository. Maybe an oversight?

**Comment by dj-on-github** [comment]
Ahh. A mistake. Bin2dec and dec2bin isn't published yet. It shouldn't be in
the makefile. Thank you. I will fix it.

**Comment by dj-on-github** [comment]
Fixed in 1.1. I blame jetlag for the error in 1.0.
